worlds:
    - world
general:
    # The time the theif should be stunned upon discovery ( in seconds )
    stun-time: 5
    # The maximal range a thief must be to keep stealing somebody.
    theft-range: 4
    # The radius around the thief where another player can detect him.
    detection-radius: 2
    # Whenever the thief can steal in other player's hotbars
    can-steal-in-hotbar: true
    # Whenever the thief can steal in non-pvp regions
    can-steal-in-non-pvp-area: false
    # Must the players have their thief level defined with permission ?
    permission-levels: false
    # The cooldown time ( in seconds )
    cooldown: 60
    # The enchantment unit multiplier - The higher this value is, the harder it will be to steal an enchanted item.
    enchantment-unit-multiplier: 0.115
language:
    enabled: "Theft have been enabled on the server."
    disabled: "Theft have been disabled on the server."
    you-have-been-discovered: "You have been discovered, and the victim stunned you with anger."
    victim-is-too-far: "The victim is too far from you."
    thief-spotted: "You feel that something is moving inside your pocket."
    cannot-rob-player: "You cannot rob this player."
    cannot-steal-in-non-pvp-area: "You cannot steal in non-PvP area."
    cooldown-not-finished: "Your cooldown is not finished."
    level-up: "You just leveled up !"